name: popcorn_time_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  floor: ^1.4.2
  fluent_ui: ^4.6.1
  introduction_screen: ^3.1.8
  flutter_animate: ^4.1.1+1
  shared_preferences: ^2.1.1
  easy_localization: ^3.0.2
  file_selector: ^0.9.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.1.2


flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/translations/
  fonts:
    - family: Estedad
      fonts:
        - asset: lib/assets/fonts/Estedad-Regular.ttf
        - asset: lib/assets/fonts/Estedad-Thin.ttf
        - asset: lib/assets/fonts/Estedad-Medium.ttf
        - asset: lib/assets/fonts/Estedad-SemiBold.ttf
        - asset: lib/assets/fonts/Estedad-Light.ttf
        - asset: lib/assets/fonts/Estedad-ExtraLight.ttf
        - asset: lib/assets/fonts/Estedad-ExtraBold.ttf
        - asset: lib/assets/fonts/Estedad-Bold.ttf
        - asset: lib/assets/fonts/Estedad-Black.ttf


